name:                advent-of-code2017
version:             0.1.0.0
github:              "githubuser/advent-of-code2017"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/advent-of-code2017#readme>

dependencies:
- base >= 4.7 && < 5
- raw-strings-qq
- containers
- vector
- free
- transformers
- strict
- parsec
- split
- mtl
- random
- array
- vector-algorithms
- monad-loops
- primitive
- kan-extensions


library:
  source-dirs: src

ghc-options:
  - -O2

executables:
  advent-of-code2017-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    # - -prof
    - -with-rtsopts=-N
    - -O2
    dependencies:
    - advent-of-code2017
  gen-bitmap-exe:
    main:                Main.hs
    source-dirs:         app/bitmap
    ghc-options:
    - -threaded
    - -rtsopts
    # - -prof
    - -with-rtsopts=-N
    - -O2
    dependencies:
    - advent-of-code2017
    - JuicyPixels
  tuper-exe:
    main:                Main.hs
    source-dirs:         app/tuper
    ghc-options:
    - -threaded
    - -rtsopts
    # - -prof
    - -with-rtsopts=-N
    - -O2
    dependencies:
    - advent-of-code2017
    - JuicyPixels
tests:
  advent-of-code2017-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - advent-of-code2017
    - "tasty"
    - "tasty-discover"
    - "tasty-hspec"
    - "tasty-quickcheck"
